version: 2.1
jobs:
  setup_and_test:
    docker:
      - image: circleci/python:2.7-stretch
      - image: circleci/python:3.5-stretch
      - image: circleci/python:3.6-stretch
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: Install Pip
          command: |
            sudo apt install python-pip
      - run:
          name: Get Environment Info
          command: |
            python -V
            pip -V
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            python ./test_pdpyras.py
workflows: 
  version: 2.1
  run_tests:
    jobs:
      - setup_and_test

